@startuml "Diagrama de Sequência - Remover Tarefa"

actor "Usuário" as User
participant "View"
participant "Controller"
participant "Model"
database "Banco de Dados" as DB

ref over User, View, Controller, Model, DB
  Diagrama de Sequência: Listar Tarefas
end ref

User ->> View : Solicitar Remoção de Tarefa
activate View

View ->> Controller : Requisição HTTP (DELETE)
deactivate View
activate Controller

Controller -> Model : Remover tarefa
activate Model

Model -> DB : Remover Tarefa (Delete com ID)
activate DB
Model <-- DB : Resultado da Operação
deactivate DB

alt Erro do Banco de Dados
    ' CASO DE ERRO 1: Falha Interna
    Controller <-- Model : Exceção de Banco de Dados
    View <-- Controller : Resposta HTTP: 500 Internal Server Error
    activate View
    User <-- View : Mensagem: "Erro interno, tente novamente"
    deactivate View
        
else Tarefa não encontrada (ID inexistente)
    ' CASO DE ERRO 2: Recurso não encontrado
    Controller <-- Model : Retorno null
    View <-- Controller : Resposta HTTP: 404 Not Found
    activate View
    User <-- View : Mensagem: "Erro: A tarefa não existe."
    deactivate View
        
else Sucesso
    ' Caminho de Sucesso
    Controller <-- Model : Tarefa removida com sucesso
    deactivate Model
        
    View <-- Controller : Resposta HTTP: 200 OK
    deactivate Controller
            
    User <-- View : Tela de confirmação de sucesso
    deactivate View
end

@enduml