@startuml "Diagrama de Classes - Componente de Tarefa"

enum Status {
    PENDENTE
    EM_ANDAMENTO
    CONCLUIDO
}

enum Tipo {
    PROVA
    TRABALHO
    ATIVIDADE
}

class Tarefa {
    -String titulo
    -String descricao
    -Date dataEntrega
    -Optional<float> nota

    +getTitulo()
    +getDescricao()
    +getDataEntrega()
    +getNota()
    +setTitulo()
    +setDescricao()
    +setDataEntrega()
    +setNota()
    +atualizarStatus(status)
}

class Lembrete {
    -Date data
    -boolean agendado

    +getData()
    +isAgendado()
    +setData(data)
    +desagendar()
}

Tarefa "1" *-- "0..*" Lembrete
Tarefa "0..*" --> "1" Status
Tipo "1" <-- "0..*" Tarefa

@enduml